name: nanoparticle-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - rdkit
  - joblib

# conda env create -f environment.yml
# conda activate nanoparticle-env
